spring:
  application:
    name: board
  profiles:
    active: dev

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


mybatis:
  config-location: classpath:mapper/config/config.xml
  mapper-locations: classpath:mapper/sql/**/*.xml